### PR TITLE
New feature addition:

### PR DESCRIPTION
**Pull request by dimpyad**
The following 3 new features have been added to this framework.
1) multipart/form-data file upload
2) application/octet-stream file upload
3) escape special chars from header if needed

Example: multipart/form-data
x-tests:
- description: Upload file to local server
steps:
- post(vars.request_body.url, vars.request_body.data,
vars.request_body.headers)
- log (res.json)

x-vars:
  request_body:
      url: http://localhost:8090
          headers:
	        content-type: multipart/form-data
		    data: ./testcases/win_gui_test.py

Example: application/octet-stream
x-tests:
- description: Upload file to dropbox server
steps:
- post(vars.dropbox_upload.url, vars.dropbox_upload.data,
vars.dropbox_upload.header)
- log (res.status)
- log (res.json)

x-vars:
 dropbox_upload:
   url: https://content.dropboxapi.com/2/files/upload
   header:
         Authorization: Bearer <token>
	 content-type: application/octet-stream
	 Dropbox-API-Arg:
           path: "/folder/file.txt"
	   mode: add
	   autorename: true
	   mute: false
	 http_header_safe:Dropbox-API-Arg
   data: file_path

### CODE REVIEW

**Comment by dimpyad** [comment]
@FrederikPriede, can you please have a look at the changes added by me and provide your input.

**Comment by FrederikPriede** [comment]
Hi @dimpyad 
thanks for contributing to got-swag. I am currently a little bit busy but i am planning to review your changes this week.

**Comment by dimpyad** [comment]
@FrederikPriede , thanks for your reply. Please review the changes whenever you get some time.

Regards,
Dimpy

**Review by FrederikPriede — APPROVED** [review]
I just reviewed your pull request. Looks fine so far, would be great if you could contribute some kind of unit test.

**Comment by dimpyad** [comment]
Thanks @FrederikPriede , I will add few unit tests as well.

**Pull request merged**
